### ISSUE TITLE
Full resource URI on HTTP Response (entity creation)

### ISSUE THREAD

**Issue by evertonberz** [FIWARE/NGSI-LD_TestSuite#3]
Hi
when creating a new entity, the spec says that upon success, the HTTP response shall include a "Location" HTTP header that contains the resource URI of the created entity resource. 
When I run my tests, I get many errors because the test suite expects only the path segment of the URI and not the full resource URI. Could you please check if this is ok? Thank you

```
Expected the object:
      {"connection": "close", "content-type": "application/json;charset=UTF-8", "date": "Wed, 28 Nov 2018 12:21:42 GMT", "location": "http://10.0.2.15:9090/ngsi-ld/v1/entities/urn:ngsi-ld:T:1543407698215", "transfer-encoding": "chunked"}
    To have a nested property:
      "location"
    With a value of:
      "/ngsi-ld/v1/entities/urn:ngsi-ld:T:1543407698215"
    Received:
      "http://10.0.2.15:9090/ngsi-ld/v1/entities/urn:ngsi-ld:T:1543407698215"
```

Regards

**Comment by jmcanterafonseca** [comment]
that's a good point, I need to check the semantics of the Location HTP header to clarify this point. 

@kzangeli what do you think?

**Comment by kzangeli** [comment]
Sounds good to me.
Actually, that is how I have implemented the Location header for orionld. And also how the "old" orion works.

**Comment by jmcanterafonseca** [comment]
As per RFC 7231 it is perfectly valid to provide only a relative URI, so the test is valid and the Orion-LD implementation is correct. If you want to allow the test to pass even the URI provided is absolute (which I don't think it is a good idea), you can modify it and make a PR. 

https://tools.ietf.org/html/rfc7231#page-68

**Comment by evertonberz** [comment]
Thank you for the feedback!
