### ISSUE TITLE
test 005 is also a bad request

### ISSUE THREAD

**Issue by ScorpioBroker** [FIWARE/NGSI-LD_TestSuite#45]
Hi,
in query_entities_error_tests in test 005 you are checking for invalid request because of the bad accept header. the way you are doing it by get <host>/ngsi-ld/entities is also a bad request because it's missing at least a type. 
Since there is not really an order in which errors should appear i would suggest to add some ?type to make it a valid request from this pov.

Benni

**Comment by jason-fox** [comment]
Fixed 39ae8727
