### ISSUE TITLE
Question on expected attributes when retrieving a subscription (test 165)

### ISSUE THREAD

**Issue by bobeal** [FIWARE/NGSI-LD_TestSuite#61]
Hi,

When I run the test 165, I get this error on the returned payload for the subscription:

```
FAIL contextSubscription/create_subscription_test.js
  Create Subscription. JSON
    ✕ should create subscription with Q Parameter 165 (105ms)

  ● Create Subscription. JSON › should create subscription with Q Parameter 165

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -3,10 +3,11 @@
          Object {
            "type": "Vehicle",
          },
        ],
        "id": "urn:ngsi-ld:Subscription:mySubscription1609080232571",
    +   "isActive": true,
        "notification": Object {
          "attributes": Array [
            "numberOfItems",
            "stocks",
            "locatedIn",
    @@ -14,10 +15,11 @@
          "endpoint": Object {
            "accept": "application/json",
            "uri": "http://tutorial:3000/subscription/low-stock-store001",
          },
          "format": "keyValues",
    +     "timesSent": 0,
        },
        "q": "numberOfItems<10;locatedIn==urn:ngsi-ld:Store:001",
        "type": "Subscription",
        "watchedAttributes": Array [
          "speed",
```

I was wondering why those 2 attributes (`isActive` and `timesSent`) are considered to be faulty. In the specification, I can't see something saying they should not be included. For `timesSent`, it is even mentioned that it is `provided by the system when querying the details of a subscription`

**Comment by kzangeli** [comment]
My guess would be that these two attributes aren't to be part of the GET payload when `true/0`.
At least, that's what I seem to have implemented in Orion-LD.
The same happens with lastFailure, lastSuccess, lastNotification, ...

**Comment by bobeal** [comment]
Hi Ken,

Thanks for your answer.

OK, I see the point ... even if I think I'll leave them in Stellio (I prefer things to be explicit) :)
